apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: nix-flakes
          command: [/var/run/argocd/argocd-cmp-server]
          image: ghcr.io/fpletz/docker-nixpkgs/nix-user:nixos-22.11
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          env:
            - name: ARGOCD_EXEC_TIMEOUT
              value: "120"
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: nix-flakes.yaml
              name: cmp-plugin
            - mountPath: /tmp
              name: cmp-tmp
      volumes:
        - configMap:
            name: cmp-plugin
          name: cmp-plugin
        - emptyDir: {}
          name: cmp-tmp
