apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  nix-flakes.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-nix-flakes-plugin
    spec:
      allowConcurrency: true
      lockRepo: false
      generate:
        command: [nix, run, '.#apps.x86_64-linux.argoGenerate']
      discover:
        find:
          command: ['nix', 'eval', '--impure', '--expr', '(builtins.getFlake (toString ./.)).apps.${builtins.currentSystem}.argoGenerate']
